
server:  port: 8888
  
spring:  application:    name: "spring-cloud-config-server"
      cloud:    config:      server:        git:          uri: file:///D:/Nikhil_File/Nikhil/microServices/git-localconfig-repo